application: barcode-share
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /TenThousandHours/css
  static_dir: TenThousandHours/css

- url: /TenThousandHours/js
  static_dir: TenThousandHours/js

- url: /TenThousandHours/scripts
  static_dir: TenThousandHours/scripts

- url: /TenThousandHours/personal\.html
  static_files: TenThousandHours/personal.html
  upload: TenThousandHours/personal.html

- url: /TenThousandHours/.*
  script: TenThousandHours.app

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: helloworld.app

libraries:
- name: jinja2
  version: latest
